import os
from PIL import Image
import threading
from PyQt5 import QtCore, QtGui, QtWidgets
from Dialog_Processing import Ui_Dialog_Processing
from CompressPicAl import EncodeImg
from Variables import Variables
class Ui_dialog_SelectPic(object):
    def setupUi(self, dialog_SelectPic, Window):
        dialog_SelectPic.setObjectName("dialog_SelectPic")
        dialog_SelectPic.setFixedSize(360, 410)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        dialog_SelectPic.setPalette(palette)
        dialog_SelectPic.setAutoFillBackground(True)
        self.label_SelectPic = QtWidgets.QLabel(dialog_SelectPic)
        self.label_SelectPic.setGeometry(QtCore.QRect(10, 5, 340, 30))
        self.label_SelectPic.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_SelectPic.setObjectName("label_SelectPic")
        self.pushButton_OpenPic = QtWidgets.QPushButton(dialog_SelectPic)
        self.pushButton_OpenPic.setGeometry(QtCore.QRect(120, 40, 121, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 170, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 170, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 170, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 170, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 85, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 170, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 170, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.pushButton_OpenPic.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_OpenPic.setFont(font)
        self.pushButton_OpenPic.setAutoFillBackground(True)
        self.pushButton_OpenPic.setObjectName("pushButton_OpenPic")
        self.groupBox_Picture = QtWidgets.QGroupBox(dialog_SelectPic)
        self.groupBox_Picture.setGeometry(QtCore.QRect(20, 80, 321, 261))
        self.groupBox_Picture.setTitle("")
        self.groupBox_Picture.setObjectName("groupBox_Picture")
        self.label_Pic = QtWidgets.QLabel(self.groupBox_Picture)
        self.label_Pic.setGeometry(QtCore.QRect(0, 0, 321, 261))
        self.label_Pic.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Pic.setObjectName("label_Pic")
        self.pushButton_Confirm = QtWidgets.QPushButton(dialog_SelectPic)
        self.pushButton_Confirm.setGeometry(QtCore.QRect(210, 360, 101, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 210, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 210, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 210, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 210, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 105, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 210, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 210, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.pushButton_Confirm.setPalette(palette)
        self.pushButton_Confirm.setAutoFillBackground(True)
        self.pushButton_Confirm.setObjectName("pushButton_Confirm")
        self.pushButton_Cancel = QtWidgets.QPushButton(dialog_SelectPic)
        self.pushButton_Cancel.setGeometry(QtCore.QRect(50, 360, 101, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 70, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 70, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 70, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 70, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 35, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 70, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 70, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.pushButton_Cancel.setPalette(palette)
        self.pushButton_Cancel.setAutoFillBackground(True)
        self.pushButton_Cancel.setObjectName("pushButton_Cancel")

        self.pushButton_OpenPic.clicked.connect(self.OpenPic)
        self.pushButton_Cancel.clicked.connect(lambda: self.clicked_Cancel(dialog_SelectPic))
        self.pushButton_Confirm.clicked.connect(lambda: self.clicked_Confirm(Window, dialog_SelectPic))

        self.Variable = Variables()
        self.LoadFonts()

        self.retranslateUi(dialog_SelectPic)
        QtCore.QMetaObject.connectSlotsByName(dialog_SelectPic)

    def retranslateUi(self, dialog_SelectPic):
        _translate = QtCore.QCoreApplication.translate
        dialog_SelectPic.setWindowTitle(_translate("dialog_SelectPic", "Select picture"))
        self.label_SelectPic.setText(_translate("dialog_SelectPic", "Select Picture"))
        self.pushButton_OpenPic.setText(_translate("dialog_SelectPic", "Open picture"))
        self.label_Pic.setText(_translate("dialog_SelectPic", "Your picture"))
        self.pushButton_Confirm.setText(_translate("dialog_SelectPic", "Confirm"))
        self.pushButton_Cancel.setText(_translate("dialog_SelectPic", "Cancel"))
    
    def LoadFonts(self):
        self.label_SelectPic.setFont(self.Variable.TLFont)
        self.label_Pic.setFont(self.Variable.LFont)
        self.pushButton_OpenPic.setFont(self.Variable.BFont)
        self.pushButton_Confirm.setFont(self.Variable.BFont)
        self.pushButton_Cancel.setFont(self.Variable.BFont)
    
    def OpenPic(self):
        Dialog = QtWidgets.QFileDialog()
        Dialog.setNameFilters(["JPEG (*.jpg;*.jpeg;*.jpe;*.jfif)","PNG (*.png)"])
        Dialog.setFileMode(QtWidgets.QFileDialog.ExistingFile)
        if Dialog.exec_() == QtWidgets.QDialog.Accepted:
            self.OpenAddress = str(Dialog.selectedFiles()[0])
            self.ShowPic()
    
    def clicked_Confirm(self, Window, dialog_SelectPic):
        try:
            self.OpenAddress
        except:
            return
        msg = QtWidgets.QMessageBox.information(dialog_SelectPic, 'Peditor', 'You have to defining us the location of the output!', QtWidgets.QMessageBox.Ok)
        filename = QtWidgets.QFileDialog()
        filename.setAcceptMode(QtWidgets.QFileDialog.AcceptSave)
        filename.setNameFilters(["JPEG (*.jpg;*.jpeg;*.jpe;*.jfif)","PNG (*.png)"])
        if filename.exec_() == QtWidgets.QDialog.Accepted:
            SavedAddress = str(filename.selectedFiles()[0])
            if Window == 'Compress':
                ProcessingDialog = QtWidgets.QDialog()
                Processing = Ui_Dialog_Processing()
                Processing.setupUi(ProcessingDialog)
                Compress = threading.Thread(target=EncodeImg, args=[self.OpenAddress, ProcessingDialog, Processing, SavedAddress, dialog_SelectPic])
                Compress.start()
                ProcessingDialog.exec_()

    def ShowPic(self):
        # size label_Pic: (321,261)
        Img = Image.open(self.OpenAddress)
        self.FinallyImage = Img
        (ximage,yimage) = Img.size
        minxy = min(321 / ximage, 261 / yimage)
        Resized_Img = Img.resize((int(ximage * minxy), int(yimage * minxy)))
        SaveAddress = "ImgShow" + self.OpenAddress[len(self.OpenAddress) - 4:]
        Resized_Img.save(SaveAddress)
        self.label_Pic.setPixmap(QtGui.QPixmap(SaveAddress))
        self.label_Pic.adjustSize()

        os.remove(SaveAddress)
    
    def clicked_Cancel(self, Dialog):
        Dialog.close()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    app.setStyle('Fusion')
    dialog_SelectPic = QtWidgets.QDialog()
    ui = Ui_dialog_SelectPic()
    ui.setupUi(dialog_SelectPic, 'Compress')
    dialog_SelectPic.show()
    sys.exit(app.exec_())
