# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ProgressBar.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Peditor(object):
    def setupUi(self, Peditor):
        Peditor.setObjectName("Peditor")
        Peditor.resize(331, 211)
        self.centralwidget = QtWidgets.QWidget(Peditor)
        self.centralwidget.setObjectName("centralwidget")
        self.progressBar_2 = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar_2.setGeometry(QtCore.QRect(30, 90, 281, 23))
        self.progressBar_2.setProperty("value", 10)
        self.progressBar_2.setObjectName("progressBar_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 10, 271, 31))
        font = QtGui.QFont()
        font.setFamily("FRIZON")
        font.setPointSize(15)
        font.setUnderline(True)
        self.label.setFont(font)
        self.label.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 60, 111, 21))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(30, 130, 101, 31))
        self.pushButton.setObjectName("pushButton")
        Peditor.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Peditor)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 331, 21))
        self.menubar.setObjectName("menubar")
        Peditor.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Peditor)
        self.statusbar.setObjectName("statusbar")
        Peditor.setStatusBar(self.statusbar)

        self.retranslateUi(Peditor)
        QtCore.QMetaObject.connectSlotsByName(Peditor)

    def retranslateUi(self, Peditor):
        _translate = QtCore.QCoreApplication.translate
        Peditor.setWindowTitle(_translate("Peditor", "MainWindow"))
        self.label.setText(_translate("Peditor", "Compress Pic"))
        self.label_2.setText(_translate("Peditor", "Compressing..."))
        self.pushButton.setText(_translate("Peditor", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Peditor = QtWidgets.QMainWindow()
    ui = Ui_Peditor()
    ui.setupUi(Peditor)
    Peditor.show()
    sys.exit(app.exec_())
