import threading
from PyQt5 import QtCore, QtGui, QtWidgets
from Dialog_Processing import Ui_Dialog_Processing
from CompressVideoAl import CompressingVideo

class Ui_dialog_SelectVideo(object):
    def setupUi(self, dialog_SelectVideo, Window):
        dialog_SelectVideo.setObjectName("dialog_SelectVideo")
        dialog_SelectVideo.setFixedSize(310, 200)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 85, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        dialog_SelectVideo.setPalette(palette)
        dialog_SelectVideo.setAutoFillBackground(True)
        self.label_SelectVideo = QtWidgets.QLabel(dialog_SelectVideo)
        self.label_SelectVideo.setGeometry(QtCore.QRect(10, 10, 281, 25))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_SelectVideo.setFont(font)
        self.label_SelectVideo.setAlignment(QtCore.Qt.AlignCenter)
        self.label_SelectVideo.setObjectName("label_SelectVideo")
        self.pushButton_OpenVideo = QtWidgets.QPushButton(dialog_SelectVideo)
        self.pushButton_OpenVideo.setGeometry(QtCore.QRect(90, 40, 121, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 170, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 170, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 170, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 170, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(25, 85, 25))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 170, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 170, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.pushButton_OpenVideo.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_OpenVideo.setFont(font)
        self.pushButton_OpenVideo.setAutoFillBackground(True)
        self.pushButton_OpenVideo.setObjectName("pushButton_OpenVideo")
        self.pushButton_Confirm = QtWidgets.QPushButton(dialog_SelectVideo)
        self.pushButton_Confirm.setGeometry(QtCore.QRect(170, 140, 101, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 210, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 210, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 210, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 210, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 105, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 210, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 210, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.pushButton_Confirm.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_Confirm.setFont(font)
        self.pushButton_Confirm.setAutoFillBackground(True)
        self.pushButton_Confirm.setObjectName("pushButton_Confirm")
        self.pushButton_Cancel = QtWidgets.QPushButton(dialog_SelectVideo)
        self.pushButton_Cancel.setGeometry(QtCore.QRect(30, 140, 101, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 70, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 70, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 70, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 70, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 35, 35))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 70, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 70, 70))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.pushButton_Cancel.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_Cancel.setFont(font)
        self.pushButton_Cancel.setAutoFillBackground(True)
        self.pushButton_Cancel.setObjectName("pushButton_Cancel")
        self.label_VideoName = QtWidgets.QLabel(dialog_SelectVideo)
        self.label_VideoName.setGeometry(QtCore.QRect(30, 80, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_VideoName.setFont(font)
        self.label_VideoName.setObjectName("label_VideoName")

        self.pushButton_OpenVideo.clicked.connect(self.OpenVideo)
        self.pushButton_Cancel.clicked.connect(lambda: self.clicked_Cancel(dialog_SelectVideo))
        self.pushButton_Confirm.clicked.connect(lambda: self.clicked_Confirm(Window, dialog_SelectVideo))

        self.retranslateUi(dialog_SelectVideo)
        QtCore.QMetaObject.connectSlotsByName(dialog_SelectVideo)

    def retranslateUi(self, dialog_SelectVideo):
        _translate = QtCore.QCoreApplication.translate
        dialog_SelectVideo.setWindowTitle(_translate("dialog_SelectVideo", "Select video"))
        self.label_SelectVideo.setText(_translate("dialog_SelectVideo", "Select Video"))
        self.pushButton_OpenVideo.setText(_translate("dialog_SelectVideo", "Open video"))
        self.pushButton_Confirm.setText(_translate("dialog_SelectVideo", "Confirm"))
        self.pushButton_Cancel.setText(_translate("dialog_SelectVideo", "Cancel"))
        self.label_VideoName.setText(_translate("dialog_SelectVideo", "Video name:"))

    def OpenVideo(self):
        Dialog = QtWidgets.QFileDialog()
        Dialog.setWindowTitle('Open Coil Definition File')
        Dialog.setNameFilters(["mp4 video (*.mp4)",
                               "wmv Video (*.wmv)",
                               "Matroska (*.mkv)",
                               "Quick Time (*.mov)",
                               "avi video (*.avi)"])
        Dialog.setFileMode(QtWidgets.QFileDialog.ExistingFile)
        if Dialog.exec_() == QtWidgets.QDialog.Accepted:
            self.OpenAddress = str(Dialog.selectedFiles()[0])
            self.UpdateVideoStatus()
    
    def UpdateVideoStatus(self):
        VideoName = self.OpenAddress.split('/')[-1]
        self.label_VideoName.setText(f'Video name: {VideoName}')
    
    def clicked_Confirm(self, Window, dialog_SelectVideo):
        try:
            self.OpenAddress
        except:
            return
        QtWidgets.QMessageBox.information(dialog_SelectVideo, 'Peditor', 'You have to defining us the location of the output!', QtWidgets.QMessageBox.Ok)
        filename = QtWidgets.QFileDialog()
        filename.setAcceptMode(QtWidgets.QFileDialog.AcceptSave)
        filename.setNameFilters(["mp4 video (*.mp4)",
                               "wmv Video (*.wmv)",
                               "Matroska (*.mkv)",
                               "Quick Time (*.mov)",
                               "avi video (*.avi)"])
        if filename.exec_() == QtWidgets.QDialog.Accepted:
            SavedAddress = str(filename.selectedFiles()[0])
            if Window == 'Compress':
                ProcessingDialog = QtWidgets.QDialog()
                Processing = Ui_Dialog_Processing()
                Processing.setupUi(ProcessingDialog)
                Compress = threading.Thread(target=CompressingVideo, args=[self.OpenAddress, ProcessingDialog, Processing, SavedAddress, dialog_SelectVideo])
                Compress.start()
                ProcessingDialog.exec_()

    def clicked_Cancel(self, Dialog):
        Dialog.close()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    app.setStyle('Fusion')
    dialog_SelectVideo = QtWidgets.QDialog()
    ui = Ui_dialog_SelectVideo()
    ui.setupUi(dialog_SelectVideo, 'Compress')
    dialog_SelectVideo.show()
    sys.exit(app.exec_())
